name: SaraSheehy
favicon: null
layout_spectrum: 0.80667
typography_spectrum: 0.8753
title: Sara Sheehy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#404548'
    - '#96979b'
    - '#101518'
    - '#626669'
    - '#cbcbcb'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
