name: SaraSheehy
favicon: null
layout_spectrum: 0.37046572542749345
typography_spectrum: 0.5503855510614812
title: Objective Reality
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3eafc'
    - '#ced5ee'
    - '#b3bdd9'
    - '#9ea7ca'
    - '#00081c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
